name: Backup Project 
on:
  push:
    branches: "main"

jobs:
  Backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Clone main to DD-MM-YYYY-test branch
        run: |
           branch_name=$(date +'%d-%m-%Y-%S')-test
           git checkout -b $branch_name
           git push --set-upstream origin $branch_name
